site_name: Auth Service Docs
theme:
  name: material
  font:
    text: Monaco
    code: Monaco
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo

nav:
  - Home: index.md
  - Diagrams:
      - Register Flow: diagrams/user-registration.md
      - Login Flow: diagrams/user-login.md
      - Refresh Token Flow: diagrams/refresh-token.md

plugins:
  - plantuml:
      diagram_root: docs/diagrams/sources
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8