name: Auth Service CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpw
          POSTGRES_DB: testdb
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Spring/Flyway/jOOQ env vars
      DB_URL: jdbc:postgresql://localhost:5432/testdb
      DB_USER: testuser
      DB_PASSWORD: testpw
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpw
      FLYWAY_URL: jdbc:postgresql://localhost:5432/testdb
      FLYWAY_USER: testuser
      FLYWAY_PASSWORD: testpw

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Run ktlint check
      - name: Run ktlint
        run: ./gradlew ktlintCheck

      # Build the app
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Build the docs
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs & PlantUML dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-puml

      - name: Build MkDocs documentation
        run: mkdocs build
